### ISSUE TITLE
Fix cryptic blueprint validation error messages

### ISSUE THREAD

**Issue by reimic** [WordPress/php-toolkit#85] opened 2024-03-19 18:56 UTC
When a blueprint fails validation a cryptic error message is returned.

For this failing blueprint (which should not fail, but that is addressed in #83):
```php
$blueprint = BlueprintBuilder::create()
    ->withWordPressVersion( 'https://wordpress.org/latest.zip' )
    ->toBlueprint();
...results in this error:
```
...this is the error message provided:
```
Array
(
    [/constants] => Array
        (
            [0] => The data (array) must match the type: object
        )

)
```
We can, and in fact - we should do better.

**Comment by adamziel** [comment] 2024-03-19 18:58
Duplicate of https://github.com/WordPress/blueprints-library/issues/83

**Closed as not planned by adamziel** 2024-03-19 18:58 UTC
Labels: enhancement
